# Generated by Django 3.0.8 on 2020-07-23 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bucket',
            name='datetocomplete',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
