# Generated by Django 3.0.8 on 2020-07-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bucket', '0002_auto_20200724_0151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='datetocomplete',
            field=models.DateField(blank=True, null=True),
        ),
    ]
